name: 'Repello Artemis Security Scanner'
description: 'Run Repello Artemis security scans on your assets'
author: 'Repello AI'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  asset_id:
    description: 'The ID of the asset to scan'
    required: true
  scan_types:
    description: 'Type(s) of scan to run. Use individual values (quick_scan, safety_scan, owasp, mitre, nist, whistleblower, fingerprint) or any comma-separated combination.'
    required: true
    default: 'quick_scan'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.asset_id }}
    - ${{ inputs.scan_types }}
