name: Test Artemis Action
description: Test the Artemis action with a self-reference

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allow manual testing
  workflow_dispatch:
    inputs:
      asset_id:
        description: 'Asset ID to scan (defaults to secret DEFAULT_ASSET_ID if not provided)'
        required: false
      scan_types:
        description: 'Type(s) of scan to run (comma-separated for multiple scans, e.g., "quick_scan,safety_scan")'
        required: true
        default: 'quick_scan,owasp'
        type: string

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Test Artemis Action (self-reference)
        uses: ./
        with:
          asset_id: ${{ github.event.inputs.asset_id || secrets.DEFAULT_ASSET_ID }}
          scan_types: ${{ github.event.inputs.scan_types || 'quick_scan,owasp' }}
        env:
          ARTEMIS_CLIENT_ID: ${{ secrets.ARTEMIS_CLIENT_ID }}
          ARTEMIS_CLIENT_SECRET: ${{ secrets.ARTEMIS_CLIENT_SECRET }}
